### ISSUE TITLE
Missing requirements

### ISSUE THREAD

**Issue by jacobwjs** [hoon9405/DescEmb#5]
Hi, just following along with your great work. 

A couple of requirements needed to setup the project are missing. Perhaps it would be good to include a basic requirements.txt file with the following packages,

easydict
transformers
iterative-stratification

and then a simple pip install -r requirements.txt could get people setup.

**Comment by hoon9405** [comment]
Hello, I am updating the yaml file related to the environment for running the pipeline. 
You can import the environment.yaml with conda.
