### ISSUE TITLE
Missing required files when running preprocess_main.py

### ISSUE THREAD

**Issue by jacobwjs** [hoon9405/DescEmb#6]
There are sections of preprocess_main.py that are commented that prevents the script from successfully completing.

e.g.
https://github.com/hoon9405/DescEmb/blob/cfee6df97722cce9a11ed30bab2dc7dee358b4dd/preprocess/preprocess_main.py#L110

which leads to the following error,
`FileNotFoundError: [Errno 2] No such file or directory: './data_input_path/mimic/mimic_cohort.pk'`

**Comment by hoon9405** [comment]
Hello, there was a serious issue with the Preprocess code, but we have now refactored the preprocess code. 
Please let us know if there are any other issues. Thank you.
